global:
  docker_repo:
  max_pod_retrials: 3
assignment:
# tameNMR
- tools_id:
   - tamenmr-addremmerge
   - tamenmr-align
   - tamenmr-anova
   - tamenmr-binning
   - tamenmr-globalalign
   - tamenmr-import_to_csv
   - tamenmr-import_to_nmrML
   - tamenmr-factorTemp
   - tamenmr-normalise_data
   - tamenmr-normalise
   - tamenmr-pca
   - tamenmr-peakpick
   - tamenmr-plotnmr
   - tamenmr-plotnmrsig
   - tamenmr-pls-da
   - tamenmr-prepPattern
   - tamenmr-quantilePlot
   - tamenmr-scaling
   - tamenmr-slice
   - tamenmr-transform
   - tamenmr-ttest
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_owner_override: phnmnl
  docker_image_override: tamenmr
  docker_tag_override: v1.0_cv0.5.10
  max_pod_retrials: 3
# Fluxomics
- tools_id: 
   - escher-fluxomics
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_owner_override: phnmnl
  docker_image_override: escher-fluxomics
  docker_tag_override: v1.6.0-beta.4_cv1.0.9
  max_pod_retrials: 3
- tools_id:
   - iso2flux
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_owner_override: phnmnl
  docker_image_override: iso2flux
  docker_tag_override: v0.7_cv2.1.52          
  max_pod_retrials: 3
- tools_id:
   - midcor
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_owner_override: phnmnl
  docker_image_override: midcor
  docker_tag_override: v1.0_cv1.0.46
  max_pod_retrials: 3
- tools_id:
   - ramid
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_owner_override: phnmnl
  docker_image_override: ramid
  docker_tag_override: v1.0_cv1.0.17
  max_pod_retrials: 3
- tools_id:
   - cdf2mid
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_owner_override: phnmnl
  docker_image_override: cdf2mid
  docker_tag_override: v1.0_cv0.3.7
  max_pod_retrials: 3

- tools_id:
   - isa_factors_viz
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_owner_override: phnmnl
  docker_image_override: mtbls-factors-viz
  docker_tag_override: v0.5_cv0.4.2.19
  max_pod_retrials: 3
  
- tools_id:
   - power-analysis
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_owner_override: phnmnl
  docker_image_override: papy
  docker_tag_override: v2.0_cv1.0.25
  max_pod_retrials: 3

- docker_image_override: mtbls-dwnld
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v4.1.3_cv2.0.34
  max_pod_retrials: 3
  tools_id:
  - mtbls-dwnld
- docker_image_override: isa-extractor
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v1.1.3_cv1.0.5
  max_pod_retrials: 3
  tools_id:
  - isa2mzml
  - isa2mzxml
  - isa2mzdata
  - isa2nmrml
  - isa2netcdf
- docker_image_override: isa2w4m
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v1.1.0_cv1.4.11
  max_pod_retrials: 1
  tools_id:
  - isa2w4m
- docker_image_override: normalization
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v1.0.6_cv1.1.2
  max_pod_retrials: 3
  tools_id:
  - normalization

- docker_image_override: transformation
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v2.2.2_cv1.2.7
  max_pod_retrials: 3
  tools_id:
  - Transformation
- docker_image_override: batch_correction
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v2.2.3_cv1.1.15
  max_pod_retrials: 3
  tools_id:
  - Batch_correction
- docker_image_override: tool-generic_filter
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: vphenomenal_2017.12.12_cv0.2.2
  max_pod_retrials: 3
  tools_id:
  - generic_filter
- docker_image_override: qualitymetrics
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v2.2.11_cv1.0.11
  max_pod_retrials: 3
  tools_id:
  - quality_metrics
- docker_image_override: biosigner
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v2.2.8_cv1.4.26
  max_pod_retrials: 3
  tools_id:
  - biosigner
- docker_image_override: openms
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v2.1.0_cv0.2.15
  max_pod_retrials: 3
  tools_id:
  - AdditiveSeries
  - BaselineFilter
  - CompNovo
  - CompNovoCID
  - ConsensusID
  - ConsensusMapNormalizer
  - Decharger
  - DTAExtractor
  - EICExtractor
  - ExternalCalibration
  - FalseDiscoveryRate
  - FeatureFinderCentroided
  - FeatureFinderIdentification
  - FeatureFinderIsotopeWavelet
  - FeatureFinderMetabo
  - FeatureFinderMRM
  - FeatureFinderMultiplex
  - FeatureLinkerLabeled
  - FeatureLinkerUnlabeled
  - FeatureLinkerUnlabeledQT
  - FidoAdapter
  - FileConverter
  - FileFilter
  - FileInfo
  - FileMerger
  - HighResPrecursorMassCorrector
  - IDConflictResolver
  - IDFileConverter
  - IDFilter
  - IDMapper
  - IDMerger
  - IDPosteriorErrorProbability
  - IDRipper
  - IDRTCalibration
  - InclusionExclusionListCreator
  - InspectAdapter
  - InternalCalibration
  - IsobaricAnalyzer
  - ITRAQAnalyzer
  - LuciphorAdapter
  - MapAlignerIdentification
  - MapAlignerPoseClustering
  - MapAlignerSpectrum
  - MapNormalizer
  - MapRTTransformer
  - MapStatistics
  - MascotAdapter
  - MascotAdapterOnline
  - MassTraceExtractor
  - MRMMapper
  - MSGFPlusAdapter
  - MyriMatchAdapter
  - MzTabExporter
  - NoiseFilterGaussian
  - NoiseFilterSGolay
  - OMSSAAdapter
  - OpenSwathAnalyzer
  - OpenSwathAssayGenerator
  - OpenSwathChromatogramExtractor
  - OpenSwathConfidenceScoring
  - OpenSwathDecoyGenerator
  - OpenSwathFeatureXMLToTSV
  - OpenSwathRTNormalizer
  - PeakPickerHiRes
  - PeakPickerWavelet
  - PepNovoAdapter
  - PeptideIndexer
  - PhosphoScoring
  - PrecursorIonSelector
  - PrecursorMassCorrector
  - ProteinInference
  - ProteinQuantifier
  - ProteinResolver
  - PTModel
  - PTPredict
  - RTModel
  - RTPredict
  - SeedListGenerator
  - SpecLibSearcher
  - SpectraFilterBernNorm
  - SpectraFilterMarkerMower
  - SpectraFilterNLargest
  - SpectraFilterNormalizer
  - SpectraFilterParentPeakMower
  - SpectraFilterScaler
  - SpectraFilterSqrtMower
  - SpectraFilterThresholdMower
  - SpectraFilterWindowMower
  - SpectraMerger
  - TextExporter
  - TMTAnalyzer
  - TOFCalibration
  - XTandemAdapter
- docker_image_override: nmrmlconv
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v1.1b_cv0.6.54
  max_pod_retrials: 3
  tools_id:
  - mtbls_nmr_raw_dummy_importer
  - nmrmlconv
  - zip-nmrml-collection
- docker_image_override: metfrag-vis
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.4.1_cv0.5.31
  max_pod_retrials: 3
  tools_id:
  - metfrag-vis
  - metfrag-vis-multiple
- docker_image_override: ecomet
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v1.1_cv0.3.39
  max_pod_retrials: 3
  tools_id:
  - ecomet_download
  - ecomet_raw_extract
  - ecomet_qc_extract
  - ecomet_quality_control
  - ecomet_preparations
  - ecomet_import_maf
  - ecomet_peak_picking
  - ecomet_import_traits
  - ecomet_species_diversity
  - ecomet_species_shannon
  - ecomet_species_unique
  - ecomet_species_variability
  - ecomet_concentration
  - ecomet_species_features
  - ecomet_species_venn
  - ecomet_species_varpart
  - ecomet_species_nmds
  - ecomet_species_marchantia
  - ecomet_ecology_varpart
  - ecomet_ecology_rda
  - ecomet_phylogeny
  - ecomet_seasons_shannon
  - ecomet_seasons_unique
  - ecomet_seasons_variability
  - ecomet_seasons_concentration
  - ecomet_seasons_features
  - ecomet_seasons_rda
  - ecomet_seasons_nmds
- docker_image_override: passatutto
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v201604_cv0.1.8
  max_pod_retrials: 3
  tools_id:
  - passatutto
- docker_image_override: metaboliteidconverter
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.5.1_cv1.1.28
  max_pod_retrials: 3
  tools_id:
  - Metabolite_ID_Converter
- docker_image_override: multivariate
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v2.3.12_cv1.3.24
  max_pod_retrials: 3
  tools_id:
  - Multivariate
- docker_image_override: mtblisa
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: latest
  max_pod_retrials: 3
  tools_id:
  - isa_get_data_files_list
  - isa_get_data_files_collection
  - isa_get_factors_summary
  - isa_get_study_factor_values
  - isa_get_study_factors
  - ISAslicer2
- docker_image_override: metfrag-cli-batch
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v2.4.5_cv0.8.71
  max_pod_retrials: 3
  tools_id:
  - metfrag-cli-batch
  - metfrag-cli-batch-multiple
- docker_image_override: ms-vfetc
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.6_cv1.1.26
  max_pod_retrials: 3
  tools_id:
  - ms-vfetc
- docker_image_override: mzquality
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.9.5_cv0.9.5.15
  max_pod_retrials: 3
  tools_id:
  - mzquality-rtshifts
  - mzquality-blank-effect
  - mzquality-qc-correction
  - mzquality-qc-rsd
  - mzquality-rep-rsd
  - mzquality-is-rsd 
  - mzquality-export-measurements   
  - mzquality-plot-compounds
- docker_image_override: rnmr1d
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v1.2.22_cv0.3.49 
  max_pod_retrials: 3
  tools_id:
  - rnmr1d
  - rnmr1d-stacked-plot
  - rnmr1d-prepare-output
- docker_image_override: nmr-integrals
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.1.1_cv0.1.17
  max_pod_retrials: 3
  tools_id:
  - nmr-integrals
- docker_image_override: metabomatching
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.2.1_cv0.5.67
  max_pod_retrials: 3
  tools_id:
  - metabomatching
- docker_image_override: iterative-signature-algorithm
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.1_cv0.1.27
  max_pod_retrials: 2
  tools_id:
  - iterative-signature-algorithm
- docker_image_override: isatab2json
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.10.0_cv0.6.1.69
  max_pod_retrials: 3
  tools_id:
  - isatab2json
- docker_image_override: batman
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v1.2.12.0_cv1.1.72 
  max_pod_retrials: 3
  tools_id:
  - batman-nmr
- docker_image_override: nmrml2batman
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v1.0_cv1.1.10
  max_pod_retrials: 3
  tools_id:
  - nmrml2batman
- docker_image_override: isodyn
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v1.0_cv0.2.48
  max_pod_retrials: 3
  tools_id:
  - isodyn
- docker_image_override: bruker2batman
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v1.0_cv1.0.14
  max_pod_retrials: 3
  tools_id:
  - bruker2batman
- docker_image_override: metfrag-cli
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v2.4.5_cv0.4.28
  max_pod_retrials: 3
  tools_id:
  - metfragcli
- docker_image_override: mw2isa
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.9.4_cv0.5.34
  max_pod_retrials: 3
  tools_id:
  - mw2isatab
- docker_image_override: nmrml2isa
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.3.0_cv0.2.12 
  max_pod_retrials: 1
  tools_id:
  - nmrml2isa
- docker_image_override: pwiz
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: latest
  max_pod_retrials: 3
  tools_id:
  - msconvert2
- docker_image_override: isatab-validator
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.10.0_cv0.7.1.42
  max_pod_retrials: 3
  tools_id:
  - isatab_validator
- docker_image_override: metabolab
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v2018.01171502_cv0.1.84
  max_pod_retrials: 3
  tools_id:
  - metabolab
- docker_image_override: lcmsmatching
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v3.4.3_cv1.5.69
  max_pod_retrials: 3
  tools_id:
  - lcmsmatching
- docker_image_override: univariate
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v2.2.6_cv1.3.32
  max_pod_retrials: 3
  tools_id:
  - Univariate
- docker_image_override: mzml2isa
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.4.28_cv0.3.26 
  max_pod_retrials: 1
  tools_id:
  - mzml2isa
- docker_image_override: xcms-1.x
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v1.52.0_cv0.9.2
  max_pod_retrials: 3
  tools_id:
  - xcms-find-peaks
  - xcms-collect-peaks
  - xcms-group-peaks
  - xcms-correct-rt
  - xcms-fill-peaks
  - xcmssplit
  - xcms-blankfilter
  - xcms-dilutionfilter
- docker_image_override: xcms
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v3.0.0_cv0.1.76
  max_pod_retrials: 1
  tools_id:
  - save_chromatogram
  - show_chromatogram
- docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_owner_override: phnmnl
  docker_image_override: pathwayenrichment
  docker_tag_override: v2.0_cv2.1.21
  max_pod_retrials: 1
  tools_id:
   - pathway_enrichment
- docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_owner_override: phnmnl
  docker_image_override: fingerprintclustering
  docker_tag_override: v3.1.2_cv1.3.12
  max_pod_retrials: 1
  tools_id:
   - fingerprint_clustering
- docker_image_override: fingerprintsubnetwork
  docker_owner_override: phnmnl
  docker_tag_override: v1.1_cv1.3.4
  max_pod_retrials: 1
  docker_repo_override: container-registry.phenomenal-h2020.eu
  tools_id:
   - fingerprint_subnetwork
- docker_image_override: scp-aspera
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v3.5.4.102989-linux-64_cv0.2.9
  max_pod_retrials: 3
  tools_id:
  - mtbls-downloader
- docker_image_override: camera
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v1.33.3_cv0.10.59
  max_pod_retrials: 3
  tools_id:
  - consensusXMLToXcms
  - cameraToFeatureXML
  - featureXMLToCAMERA
  - featureXMLToXcms
  - zip-collection
  - unzip-collection
  - camera-annotate-peaks
  - camera-group-fwhm
  - camera-group-corr
  - camera-find-isotopes
  - camera-find-adducts
  - camera-prepareoutput
- docker_image_override: msnbase
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v2.2_cv0.9.61
  max_pod_retrials: 3
  tools_id:
  - msnbase-read-msms
  - map-msms2camera
  - msms2metfrag
  - msms2metfrag-multiple
  - msnbase-filter-merge-msms
  - aggregatemetfrag
- docker_image_override: mtbl-labs-uploader
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.1.1_cv0.5.15
  max_pod_retrials: 3
  tools_id:
  - mtbls-labs-uploader
- docker_image_override: isatab-create
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.10.2_cv0.5.4.81
  max_pod_retrials: 3
  tools_id:
  - isacreate_metabo
- docker_image_override: dimspy
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v1.1.0_cv1.1.13
  max_pod_retrials: 3
  tools_id:
  - dimspy_process_scans
  - dimspy_replicate_filter
  - dimspy_align_samples
  - dimspy_blank_filter
  - dimspy_sample_filter
  - dimspy_hdf5_to_txt
  - dimspy_merge_peaklists
  - dimspy_get_peaklists
- docker_image_override: ipo
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: latest
  max_pod_retrials: 3
  tools_id:
  - ipo4xcmsSet
  - ipo4retgroup
- docker_image_override: reshape2-melt
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.1_cv0.1.1.3
  max_pod_retrials: 3
  tools_id:
  - melt
- docker_image_override: reshape2-cast
  docker_owner_override: phnmnl
  docker_repo_override: container-registry.phenomenal-h2020.eu
  docker_tag_override: v0.1_cv0.1.1.3
  max_pod_retrials: 3
  tools_id:
  - cast
